### ISSUE TITLE
Integrate with Travis CI

### ISSUE THREAD

**Issue by fanky10** [adsf117/Clean_Marvel_Kotlin#2]
Just integrate to Travis CI, to avoid future breaking build PR

**Comment by adsf117** [comment]
@fanky10  bad new bro, for the moment travis don't support  Kotlin language  https://github.com/travis-ci/travis-ci/issues/7833

**Comment by fanky10** [comment]
I don't want to tell you otherwise, but I can show it to you:

https://travis-ci.org/fanky10/mvp_unit_tests/builds/346539108

**Comment by adsf117** [comment]
sweet! thxs!

**Comment by adsf117** [comment]
@fanky10 here the PR for travis CI integration https://github.com/adsf117/Clean_Marvel_Kotlin/pull/3
Best regards!
